[FAILS] Refactor: make it fail better
Now we can see the correct failure site:

	Xunit.Sdk.TrueException
	System.ArgumentNullException: Value cannot be null. (Parameter 's')
	   at System.ArgumentNullException.Throw(String paramName)
	   at System.Text.Encoding.GetBytes(String s)
	   at Letterbook.Api.Controllers.UserAccountController.Login(LoginRequest loginRequest) in

So it *is* failing due to missing host secret.

@todo: there is a general problem here with any request that throws an
exception. I suspect whenever that happens you'll that serialization
error:

	System.NotSupportedException: Serialization and deserialization of 'System.Reflection.MethodBase' instances is not supported.