Ignore 'CoreEventId.ManyServiceProvidersCreatedWarning' here, too
Resolves intermittent test failures like:

 Letterbook.IntegrationTests test failed with 6 error(s) (42.6s)
    C:\Users\BenBiddington\sauce\Letterbook\Source\Letterbook.Adapter.TimescaleFeeds\FeedsContext.cs(16): error TESTERROR:
      Should remove a post from all timelines (1ms): Error Message: Class fixture type 'Letterbook.IntegrationTests.Fixtures.TimescaleDataFixture`1[[Letterbook.IntegrationTests.FeedsAdapterTest, Letterbook.IntegrationTests, Version=1.0.0.0, Culture=neutral, PublicKeyTo
      ken=null]]' threw in its constructor
      ---- System.InvalidOperationException : An error was generated for warning 'Microsoft.EntityFrameworkCore.Infrastructure.ManyServiceProvidersCreatedWarning': More than twenty 'IServiceProvider' instances have been created for internal use by Entity Framework. Thi
      s is commonly caused by injection of a new singleton service instance into every DbContext instance. For example, calling 'UseLoggerFactory' passing in a new instance each time--see https://go.microsoft.com/fwlink/?linkid=869049 for more details. This may lead to
       performance issues, consider reviewing calls on 'DbContextOptionsBuilder' that may require new service providers to be built. This exception can be suppressed or logged by passing event ID 'CoreEventId.ManyServiceProvidersCreatedWarning' to the 'ConfigureWarning
      s' method in 'DbContext.OnConfiguring' or 'AddDbContext'.
      Stack Trace:

      ----- Inner Stack Trace -----
         at Microsoft.EntityFrameworkCore.Diagnostics.EventDefinition.Log[TLoggerCategory](IDiagnosticsLogger`1 logger, Exception exception)
         at Microsoft.EntityFrameworkCore.Diagnostics.CoreLoggerExtensions.ManyServiceProvidersCreatedWarning(IDiagnosticsLogger`1 diagnostics, ICollection`1 serviceProviders)
         at Microsoft.EntityFrameworkCore.Internal.ServiceProviderCache.<GetOrAdd>g__BuildServiceProvider|4_1(IDbContextOptions _, ValueTuple`2 arguments)
         at Microsoft.EntityFrameworkCore.Internal.ServiceProviderCache.<>c.<GetOrAdd>b__4_0(IDbContextOptions contextOptions, ValueTuple`2 tuples)
         at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd[TArg](TKey key, Func`3 valueFactory, TArg factoryArgument)
         at Microsoft.EntityFrameworkCore.Internal.ServiceProviderCache.GetOrAdd(IDbContextOptions options, Boolean providerRequired)
         at Microsoft.EntityFrameworkCore.DbContext..ctor(DbContextOptions options)
         at Letterbook.Adapter.TimescaleFeeds.FeedsContext..ctor(DbContextOptions`1 options) in C:\Users\BenBiddington\sauce\Letterbook\Source\Letterbook.Adapter.TimescaleFeeds\FeedsContext.cs:line 16
         at Letterbook.Adapter.TimescaleFeeds._Tests.Fixtures.TimescaleFixture`1.CreateContext() in C:\Users\BenBiddington\sauce\Letterbook\Tests\Letterbook.Adapter.TimescaleFeeds.Tests\Fixtures\TimescaleFixture.cs:line 30
         at Letterbook.IntegrationTests.Fixtures.TimescaleDataFixture`1..ctor(IMessageSink sink) in C:\Users\BenBiddington\sauce\Letterbook\Tests\Letterbook.IntegrationTests\Fixtures\TimescaleFixture.cs:line 26
         at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
         at System.Reflection.MethodBaseInvoker.InvokeDirectByRefWithFewArgs(Object obj, Span`1 copyOfArgs, BindingFlags invokeAttr)